Feat: pop install
r0gue-io/pop-cli pull request #127
Opened 2024-05-01 07:07 UTC by weezy20

Setup substrate development environment. 
Closes #110

2024-05-06 08:26 UTC, AlexD10S reviewed
Code looks good (just few comments), but the script needs more user testing, in a Mac OS (Darwin) I get an error:
`error: failed to set permissions for '/Users/alexbean/.cargo/bin/rustup-init': No such file or directory (os error 2)`

After this PR, next steps has to be have this functionality in Rust code to improve UX: We can have better customization on the user messages (Instead of the echo, see this PR: https://github.com/r0gue-io/pop-cli/pull/123), also prompt the user to pick what they want/don't want to install....

2024-05-06 08:26 UTC, AlexD10S commented on crates/pop-cli/src/commands/install/mod.rs
> +		Command::new("bash").arg(scripts_path).status().await?;
We used `duct::cmd` to run cargo test in the test smart contract functionality.

2024-05-06 08:26 UTC, AlexD10S commented on crates/pop-cli/src/commands/install/mod.rs
> +			return Ok(cliclack::log::error("Windows is supported only with WSL2")?);
Should we add a URL for more info? https://docs.substrate.io/install/windows/

2024-05-06 08:26 UTC, AlexD10S commented on crates/pop-cli/src/main.rs
> +	/// Install prerequisites for Substrate development
I like _Set up the environment for Substrate development_ more. But up to you to decide

2024-05-07 10:13 UTC, brunopgalvao commented
If we are going to make edits to the `get_substrate` script, I advocate we replace it with Rust code (as we were already planning on doing so).

2024-05-07 22:15 UTC, peterwht commented on scripts/get_substrate.sh
> +	brew install openssl cmake llvm
needs to include `protobuf`

2024-05-07 22:19 UTC, peterwht requested changes
Looks mostly good! A few changes I would like to see for this first version:
- protobuf needs to be included for mac
- there should be a question at the start saying "this will attempt to install the following components: <components>. do you want to proceed?"

Long term, it would be nice to not use a .sh script and have it entirely in code. But let's see how useful this command is first before furhter improving on it :)

2024-05-10 13:10 UTC, closed without merging