chore: polkadot v1.10.0
r0gue-io/pop-cli pull request #171
Opened 2024-05-15 06:56 UTC by Daanvdplas

The mock.rs file had a change coming from the v1.10 upgrade. The Cargo.toml files had both one as well (codec). Right now I changed everything to workspace dependencies which would be ideal. However, when someone creates a new project the `pallets/` folder is not yet added to the workspace in the root Cargo.toml file. Putting it here to get your opinion and see if it can easily be resolved.

2024-05-16 08:32 UTC, AlexD10S commented on crates/pop-parachains/templates/base/runtime-cargo.templ
>  [package]
runtime-cargo.templ and runtime.templ are not being used. My suggestion would be remove them to don't mantain dead code

2024-05-16 08:36 UTC, AlexD10S requested changes

2024-05-18 10:13 UTC, Daanvdplas commented on crates/pop-parachains/templates/pallet/Cargo.templ
> +frame-benchmarking.workspace = true
Yes so if we could add `pallets/` as a workspace member when we add a pallet, this is resolved

2024-05-18 10:23 UTC, Daanvdplas commented on crates/pop-parachains/templates/pallet/Cargo.templ
> +frame-benchmarking.workspace = true
This is something for later because I see pop add pallet does not exist and then this does not make sense

2024-05-18 11:22 UTC, Daanvdplas commented
I want to update the links in the pallet template because they are outdated. Will finish as soon as I know where

2024-05-20 12:59 UTC, AlexD10S approved these changes

2024-05-20 16:40 UTC, merged