fix: improve contract experience
r0gue-io/pop-cli pull request #330
Opened 2024-10-31 14:18 UTC by AlexD10S

- [x] Partially addresses https://github.com/r0gue-io/pop-cli/issues/290. The `code_hash` is now displayed when running `pop up contract` for both upload only (`-u`) and upload + instantiate scenarios.

For instantiating an already uploaded contract, `code_hash` is currently not displayed, as retrieving it would require parsing events or querying the value on-chain.

- [X] Additionally, this PR closes https://github.com/r0gue-io/pop-cli/issues/291

It adds `-lerror,runtime::contracts=debug` when running `substrate-contracts-node` to allow debugging messages (the contract has to be build without --release flag).

TODO:

- [ ] https://github.com/r0gue-io/pop-cli/issues/319

2024-11-05 13:06 UTC, evilrobot-01 requested changes
Looks good, various minor improvements and clippy warnings to address and then I'm good to approve.

2024-11-05 13:06 UTC, evilrobot-01 commented on crates/pop-contracts/src/up.rs
> +	let hash = if let Some(code_hash) = instantiate_result.code_hash {
Address clippy warning.

2024-11-05 13:06 UTC, evilrobot-01 commented on crates/pop-cli/src/commands/up/contract.rs
> +					.to_string(),
Address clippy warning

2024-11-05 13:06 UTC, evilrobot-01 commented on crates/pop-cli/src/commands/up/contract.rs
> +						"{} The Contract Address is {:?}",
```suggestion
						"{} The contract address is {:?}",
```

2024-11-05 13:06 UTC, evilrobot-01 commented on crates/pop-cli/src/commands/up/contract.rs
> +							"{} The Contract Code Hash is {:?}",
```suggestion
							"{} The contract code hash is {:?}",
```

2024-11-06 10:19 UTC, AlexD10S commented
> For some reason the logs are empty. Is this the correct log path?

Exactly. If the contract has already been uploaded, retrieving the code_hash is a bit more complex. I left it out for now, but we can handle it later by parsing events or querying on-chain.

As for the logs, they are working. 
Keep in mind that the contract must be built without the `--release` flag to display debug logs (see [Ink! Debugging Guide](https://use.ink/basics/contract-debugging/#how-do-i-print-to-the-terminal-console-from-ink)). Also, note that the proposed `-lerror,runtime::contracts=debug` flag only shows error and debug output. If we need more verbosity, I can switch it to `-linfo,runtime::contracts=debug` to include all info logs.

2024-11-06 17:19 UTC, al3mart approved these changes
I see the feedback has been included.
I don't have much more to point out rather than a small nit. But definitely not blocking the merge.

![image](https://github.com/user-attachments/assets/04e44056-10ab-4e50-90f4-cc1db2d6e7a4)

The emojis are not colored like  the rest of the prompt is :P
Aside from that, I would assume that a user that can instantiate some code has access to the code and could obtain the hash easily. Though, I agree that being consistent and showing it every time would be the best experience.

2024-11-06 21:56 UTC, evilrobot-01 approved these changes

2024-11-06 21:56 UTC, evilrobot-01 commented on crates/pop-contracts/src/up.rs
> +///Type to represent information about a deployed smart contract.
```suggestion
/// Type to represent information about a deployed smart contract.
```

2024-11-07 02:08 UTC, brunopgalvao commented
> Also, note that the proposed `-lerror,runtime::contracts=debug` flag only shows error and debug output. If we need more verbosity, I can switch it to `-linfo,runtime::contracts=debug` to include all info logs.

I think more verbosity would nice.

2024-11-07 02:09 UTC, brunopgalvao approved these changes

2024-11-07 14:27 UTC, AlexD10S commented
> > Also, note that the proposed `-lerror,runtime::contracts=debug` flag only shows error and debug output. If we need more verbosity, I can switch it to `-linfo,runtime::contracts=debug` to include all info logs.
> 
> I think more verbosity would nice.

Agree. Makes sense to have `info`

2024-11-08 02:15 UTC, brunopgalvao approved these changes

2024-11-08 08:03 UTC, merged

2024-11-12 04:08 UTC, brunopgalvao commented
closes https://github.com/r0gue-io/pop-cli/issues/319